services:
  - type: web
    name: assistive-vision-app
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=10000 --server.address=0.0.0.0
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_ENABLECORS
        value: "false"
      - key: STREAMLIT_SERVER_PORT
        value: "10000"
      - key: STREAMLIT_SERVER_ADDRESS
        value: "0.0.0.0"
